// Copyright (c) 2019 dpvreony and Contributors. All rights reserved.
// This file is licensed to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System;
using System.CommandLine;
using System.IO;

namespace NetTestRegimentation.IntegrationTests
{
    /// <summary>
    /// Helpers for testing command line applications using xUnit.
    /// </summary>
    public static class XUnitTestHelpers
    {
        /// <summary>
        /// Creates a test configuration for integrating a console application with command-line functionality.
        /// </summary>
        /// <param name="outputWriter">A <see cref="StringWriter"/> instance used to capture standard output generated by the command-line interface.</param>
        /// <param name="errorWriter">A <see cref="StringWriter"/> instance used to capture error output generated by the command-line interface.</param>
        /// <returns>Invocation configuration for capturing console stdio into XUnit.</returns>
        public static InvocationConfiguration CreateTestConsoleIntegration(
            StringWriter outputWriter,
            StringWriter errorWriter)
        {
            ArgumentNullException.ThrowIfNull(outputWriter);
            ArgumentNullException.ThrowIfNull(errorWriter);

            return new InvocationConfiguration
            {
                Error = errorWriter,
                Output = outputWriter
            };
        }
    }
}
